package org.saharsh.gupchup.server.model;

public enum RelationshipStatus {
	CONNECTION_REQUEST_SENT, CONNECTION_REQUEST_RECEIVED, CONNECTION_REJECTION_SENT, CONNECTION_REJECTION_RECEIVED,
	CONNECTED, BLOCK_SENT, BLOCK_RECEIVED
}